apiVersion: 1

datasources:
  - name: Graphite
    type: graphite
    access: proxy
    url: http://172.22.0.3:80
    isDefault: true
    editable: true
    jsonData:
      graphiteVersion: "1.1"
      httpMethod: POST
    secureJsonData: {}
